### ISSUE TITLE
possible Fahrenheit conversion issue

### ISSUE THREAD

**Issue by ac4lt** [pdemarco925/homebridge-icomfort#7]
I'm early in trying this so perhaps am doing something wrong, but when I adjust the thermostat in HomeKit to a temperature, say, for example, 75F, I see the homebridge console say it's setting to 74.3. If I have the myicomfort webpage open I see the set point change, briefly, to 74.3 and then it reverts to the previous value. 

I'm guessing HomeKit works with Celsius internally and we've got a conversion from F to C to F going on and the resulting decimal number isn't really acceptable to comfort. Perhaps it needs to round to the nearest integer before attempting to change the set point. The homebridge plugin and the thermostat are out of sync at this point. The plugin thinks the set point has changed but the thermostat doesn't.

If I set to 69, it's sending 69.08 to comfort which actually got accepted so I'm not sure why some are accepted and others aren't.

**Comment by pdemarco925** [comment]
I haven't had time to try to figure out where the conversions are being applied and how/where/if rounding would help. I know even using the iPhone Lennox iComfort app when you attempt to select a new temp it sometimes rolls back to the old temp. The real issue is the underlying library I leverage/wrap is using Lennox's older API. The author hasn't had time to update to the new API which would allow homebridge to get the rollback so they can at least stay in synch.

**Comment by AdrianCalifornia** [comment]
Any chance on an update to this? I noticed while setting automations for day/night temperatures there can be 1-4 degree variance on what I set vs what temperate gets set. Thanks

**Comment by pdemarco925** [comment]
Just updated to release 2.0.0, try and see if the updates work for you.
I had to make updates due to dependencies changing, Siri and HomeKit act differently now then when i originally developed it. Let me know if you see any issues.
